// Generated by scripts/embed-portfolio.py; only approved public assets.
fn serve_portfolio_asset(path: &str) -> Option<Response> {
    match path {
        "/static/portfolio/media/ai-reply.mp3" => Some(bytes_response(include_bytes!("../../static/portfolio/media/ai-reply.mp3"), "audio/mpeg")),
        "/static/portfolio/media/hook.mp3" => Some(bytes_response(include_bytes!("../../static/portfolio/media/hook.mp3"), "audio/mpeg")),
        "/static/portfolio/media/portfolio-bim.png" => Some(bytes_response(include_bytes!("../../static/portfolio/media/portfolio-bim.png"), "image/png")),
        "/static/portfolio/media/portfolio-jiuflow.png" => Some(bytes_response(include_bytes!("../../static/portfolio/media/portfolio-jiuflow.png"), "image/png")),
        "/static/portfolio/media/portfolio-koe.png" => Some(bytes_response(include_bytes!("../../static/portfolio/media/portfolio-koe.png"), "image/png")),
        "/static/portfolio/media/portfolio-mu.png" => Some(bytes_response(include_bytes!("../../static/portfolio/media/portfolio-mu.png"), "image/png")),
        "/static/portfolio/media/portfolio-news.png" => Some(bytes_response(include_bytes!("../../static/portfolio/media/portfolio-news.png"), "image/png")),
        "/static/portfolio/media/portfolio-sente.png" => Some(bytes_response(include_bytes!("../../static/portfolio/media/portfolio-sente.png"), "image/png")),
        "/static/portfolio/media/portfolio-stayflow.png" => Some(bytes_response(include_bytes!("../../static/portfolio/media/portfolio-stayflow.png"), "image/png")),
        "/static/portfolio/media/portfolio-teai.png" => Some(bytes_response(include_bytes!("../../static/portfolio/media/portfolio-teai.png"), "image/png")),
        "/static/portfolio/portfolio-polish.css" => Some(bytes_response(include_bytes!("../../static/portfolio/portfolio-polish.css"), "text/css; charset=utf-8")),
        "/static/portfolio/portfolio.pdf" => Some(bytes_response(include_bytes!("../../static/portfolio/portfolio.pdf"), "application/pdf")),
        "/static/portfolio/share.png" => Some(bytes_response(include_bytes!("../../static/portfolio/share.png"), "image/png")),
        _ => None,
    }
}
