"""Generate the explicit public asset allowlist used by the Spin component."""
from pathlib import Path

root = Path(__file__).resolve().parent.parent
types = {'.css': 'text/css; charset=utf-8', '.png': 'image/png', '.mp3': 'audio/mpeg', '.pdf': 'application/pdf', '.html': 'text/html; charset=utf-8', '.txt': 'text/plain; charset=utf-8'}
lines = ['// Generated by scripts/embed-portfolio.py; only approved public assets.',
         'fn serve_portfolio_asset(path: &str) -> Option<Response> {', '    match path {']
for file in sorted((root / 'static/portfolio').rglob('*')):
    if not file.is_file():
        continue
    relative = file.relative_to(root).as_posix()
    content_type = types[file.suffix]
    lines.append(f'        "/{relative}" => Some(bytes_response(include_bytes!("../../{relative}"), "{content_type}")),')
lines += ['        _ => None,', '    }', '}', '']
(root / 'spin-component/src/portfolio_assets.rs').write_text('\n'.join(lines))
print('Embedded', len(lines) - 7, 'public assets')
